# Generated by Django 5.0.3 on 2024-04-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('texto', models.TextField()),
                ('noticia', models.TextField()),
                ('data', models.DateField(help_text='dd/mm/yyyy')),
            ],
        ),
    ]
