# Generated by Django 5.0.3 on 2024-04-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('data', models.DateField(help_text='dd/mm/aaaa')),
                ('categoria', models.CharField(choices=[('Esporte', 'Esporte'), ('Cultura', 'Cultura'), ('Economia', 'Economia')], max_length=50)),
                ('conteudo', models.TextField()),
                ('destaque', models.BooleanField()),
                ('imagem', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=50)),
            ],
        ),
    ]
