# Generated by Django 5.0.3 on 2024-04-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autora',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
