# Generated by Django 4.2.11 on 2024-04-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_alter_noticia_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autora',
        ),
    ]
