# Generated by Django 4.2.11 on 2024-04-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0010_alter_noticia_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('Esporte', 'Esporte'), ('Cultura', 'Cultura'), ('Economia', 'Economia'), ('Politica', 'Politica'), ('Tecnologia', 'Tecnologia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default='Pendente', max_length=50),
        ),
    ]
