# Generated by Django 5.0.3 on 2024-04-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('senha', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Master', 'Master'), ('Autor', 'Autor'), ('Editor', 'Editor')], max_length=8)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
